print("Hello to Python Calculator!")
print("Choose any one of the operation.")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
print("5. Modulus")
print("6. Exit")
input= int(input("Enter your choice: "))